import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import 'mapbox-gl/dist/mapbox-gl.css';
import { Instrument_Sans } from 'next/font/google'

const sans = Instrument_Sans({
  subsets: ['latin'],
  display: 'swap',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sans.className}>
      <body
      >
        {children}
      </body>
    </html>
  );
}
